name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: deploy
        run: echo Deploy to DEV

  deploy-to-uat:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: deploy
        run: echo Deploy to UAT

  deploy-to-prod:
    needs: deploy-to-uat
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - name: deploy
        run: echo Deploy to PROD
        